<template>
  <div class="container is-widescreen">
    <div id="page">
      <div id="header">
        <span id="logo"><img src="dist/sundawn.png" alt="Welcome to the DAAWN tool" id="daawn-logo"></span>
        <p class="title is-3">Digitised Assessment for Aphasia of Written Naming (DAAWN)</p>
        <p class="title is-4">Using the tool</p>
      </div>

      <p class="text">DAAWN is an assessment of single word naming for use with keyboard or touchscreen input via a web browser on any computer or mobile device. The assessment does not currently require any registration on the part of the user and does not collect or keep any of the assessment data. The SLT can choose from one of four stimulus picture sets to carry out the assessment. Click for information about <a href="#" @click="showSetsModal = true">word sets</a>.</p>

      <p class="text special">Data generated by DAAWN</p>

      <p class="text">DAAWN will automatically calculate the number of items correctly named and will provide you with a range of other information you may find relevant as part of your assessment, e.g. timings, automated scoring, and a record of the process by which a person reaches their final response. When your assessment is complete, DAAWN generates an anonymised report, which will be a PDF download. We advise that you do not use the tool on devices that do not belong you to you or to your employer as you would then need to transfer the document to your own device. </p>

      <p class="text">The <span class="special">process response</span> records the keys pressed by the client when typing the word. This allows the SLT to see whether errors have been self-corrected during the typing process. It will also record any pause longer than one second. For example, the word ‘anchor’ could be typed as follows: [a, n, k, Backspace, c, (2.3secs), o, r] with the end result ‘ancor’.</p>

      <p class="text special">Scoring</p>

      <p class="text">The application automatically calculates a score based on the system used in the writing section of the Comprehensive Aphasia Test. It also provides a score of Damerau-Levenshtein distance. Click for more information about <a href="#" @click="showAboutLDModal = true">Damerau-Levenshtein distance</a>. </p>

      <p class="text">Both CAT and LD scoring is automatically calculated from the person's <span class="text">final response</span>. This includes items where the first letter has been provided by a hint. Where a hint was given, items are denoted with an [*] in the assessment results. </p>

      <p class="text special">Images</p>

      <p class="text">The photographs used as stimulus images in DAAWN were initially selected as part of a PhD research project by <span class="special">Dr Ella Creet</span> and were obtained from various sources: <cite>Hemera Photo Object Library (Hemera Technologies Inc, 1997-2000)</cite>, Newcastle University picture library or from other open access sources.</p>


      <div class="level" >
        <div class="level-item">

          <AboutLDModal v-if="showAboutLDModal"  @close="showAboutLDModal = false"  />
          <SetsModal v-if="showSetsModal"  @close="showSetsModal = false"  />

          <p class="highlight special">Click <strong>Next</strong> to select your options</p>
        </div>
        <div class="level-item">
          <div class="buttons-section">
            <button class="button exit-btn" @click=exit()>Exit</button>
            <button class="button next-btn" @click=next()>Next</button>
          </div>

        </div>
      </div>

      <ExitModal v-if="showExitModal" @close="showExitModal = false" />
    </div>
  </div>
</template>

<script>

  import AboutLDModal from './AboutLDModal';
  import SetsModal from "./SetsModal";
  import ExitModal from "./ExitModal";

    export default {
        name: "AppInfo",
        components: {
          AboutLDModal,
          SetsModal,
          ExitModal
        },
        data() {
            return {
              showAboutLDModal : false,
              showSetsModal : false,
              showExitModal : false
            }
        },
        methods: {
            exit() {
                this.showExitModal = true;
            },
            next() {
              this.$router.push({ path: './select' });
            }
        }
    }
</script>

<style scoped>
  #page {
    border: 1px solid #c4c4c4;
    border-radius: 25px;
    margin: 50px;
    background-color: #fff;
    padding: 30px;
  }

  #header {
    padding-bottom: 20px;
  }


  #logo {
    float:right;
  }

  #daawn-logo {
    height: 40px;
  }

</style>
